---
title: "dWaSSI-C document"
output: 
  html_notebook: 
    number_sections: yes
    toc: yes
---

# Introduction

This document demonstrates the main functionality of the dWaSSIC package. 

# load required document
```{r}
# load devtools package for installing github packages
  if("devtools" %in% installed.packages()){
    library(devtools)
  }else{
    install.packages("devtools")
    library(devtools)
  }

# Install dWaSSIC package from github
  if("dWaSSI" %in% installed.packages()){
    library(dWaSSI)
  }else{
    install_github("ln1267/dWaSSI")
    library(dWaSSI)
  }

# Load other required packages
f_lib_check(c("raster","reshape2","parallel","lubridate"))
```

# Test run
```{r}
Climate<-read.csv("~/dWaSSIC_R/tmp/CLIMATE.TXT")
LAI<-read.csv("~/dWaSSIC_R/tmp/LANDLAI.TXT")
SOIL<-read.csv("~/dWaSSIC_R/tmp/SOILINFO.TXT")
HUC<-read.csv("~/dWaSSIC_R/tmp/CELLINFO.TXT")

Climate<-read.csv("~/Downloads/FOR_NING/INPUTS/R1_PRISM_CLIMATE.TXT")
LAI<-read.csv("~/Downloads/FOR_NING/INPUTS/LANDLAI_CONUSF2F.txt")
SOIL<-read.csv("~/Downloads/FOR_NING/INPUTS/SOILINFO_US_HUC12.TXT")
HUC<-read.csv("~/Downloads/FOR_NING/INPUTS/CELLINFO_CONUSF2F.txt")

names(Climate)<-c("BasinID","Year","Month","Ppt_mm","Tavg_C")
names(SOIL)[1]<-c("BasinID")

names(LAI)[1:2]<-c("BasinID","Year")
names(HUC)[1:2]<-c("ID","BasinID")

LAI<-cbind(Year=2000,LAI)
names(LAI)[2:3]<-c("BasinID","Month")
names(HUC)[1]<-c("BasinID")

# Filter data based on climate data
BasinIDs<-unique(Climate$BasinID)[1:100]
NBasins<-length(BasinIDs)

Climate<-Climate[Climate$BasinID %in% BasinIDs,]
HUC<-HUC[HUC$BasinID %in% BasinIDs,]
LAI<-LAI[LAI$BasinID %in% BasinIDs,]
SOIL<-SOIL[SOIL$BasinID %in% BasinIDs,]

# Set period for simulation
str_date <- as.Date("2001/01/01") 
end_date <- as.Date("2012/12/01") 

# Climate time range
str_date_input <- as.Date(paste0(min(Climate$Year),"/01/01"))
end_date_input <- as.Date(paste0(max(Climate$Year),"/12/01"))


# LAI time range
str_date_lai <- as.Date(paste0(min(LAI$Year),"/01/01")) 
end_date_lai <- as.Date(paste0(max(LAI$Year),"/12/01")) 

seq_date<-seq.Date(str_date,end_date,by = "month")
seq_datef<-seq.Date(str_date_input,end_date_input,by = "month")
sim_ind <-which(seq_datef %in% seq_date)

par_sacsma   = as.matrix(SOIL[,2:12] )
colnames(par_sacsma)<-toupper(colnames(par_sacsma))
par_petHamon = rep(1,NBasins)
# par_snow17   = stcroix$hru.par[,18:27] 
# par_routLah  = stcroix$hru.par[,28:31] 

clim_prcp<-matrix(Climate$Ppt_mm,ncol=NBasins)
clim_tavg<-matrix(Climate$Tavg_C,ncol=NBasins)

hru_lc_lai<-lapply(BasinIDs, function(x) as.matrix(subset(LAI,BasinID==x)[c(4:length(LAI[1,]))]))

huc_lc_ratio<-as.matrix(HUC[c(8:length(HUC[1,]))])
hru_info<-HUC[c(1:7)]
names(hru_info)<-c("ID","BasinID","HRU_Area","HRU_Lat","HRU_Lon","HRU_Elev(m)","HRU_FlowLen(m)")

huc_lc_ratio<-as.matrix(HUC[c(4:length(HUC[1,]))])
hru_info<-HUC[c(1:3)]
names(hru_info)<-c("BasinID","HRU_Lat","HRU_Lon")


flowR <- dWaSSIC(str.date = str_date, end.date = end_date, warmup = 3,mcores = 3,
             str.date.climate =str_date_input, end.date.climate  = end_date_input, 
             par.sacsma = par_sacsma,par.petHamon=par_petHamon, 
             hru.info = hru_info, 
             clim.prcp = clim_prcp, clim.tavg = clim_tavg,
             hru.lai=NULL,hru.lc.lai=hru_lc_lai,huc.lc.ratio=huc_lc_ratio,
             str.date.lai =str_date_lai, end.date.lai  = end_date_lai) 



flowR <- distHydroSim(str.date = str_date, end.date = end_date, 
             str.date.climate =str_date_input, end.date.climate  = end_date_input, 
             par.sacsma = par_sacsma,par.petHamon=par_petHamon, par.snow17=par_snow17,par.routLah=par_routLah,
             hru.info = hru_info, hru.elevband = NULL, 
             clim.prcp = clim_prcp, clim.tavg = clim_tavg,
             hru.lai=NULL,hru.lc.lai=hru_lc_lai,huc.lc.ratio=huc_lc_ratio,
             str.date.lai =str_date_lai, end.date.lai  = end_date_lai, 
             snow.flag = 0, progress.bar = TRUE,month=T) 

Rain_mean<-apply(clim_prcp, 1, mean,na.rm=T)
df <- data_frame(date = seq_date,Totflow=flowR$OUT$tot, TotET=flowR$OUT$totaet,Srufflow = flowR$SURF,Baseflow=flowR$BASE,Rain=Rain_mean[sim_ind])
ggplot(df, aes(date, Totflow)) + geom_line() + labs(x = "", y = "Surface flow (mm/month)")
ggplot(df, aes(date, Rain)) + geom_line() + labs(x = "", y = "Rain (mm/month)")
ggplot(df1, aes(date, Totflow)) + geom_line() + labs(x = "", y = "Surface flow (mm/month)")
ggplot(df, aes(date, TotET)) + geom_line() + labs(x = "", y = "ET (mm/month)")
ggplot(df1, aes(date, TotET)) + geom_line() + labs(x = "", y = "ET (mm/month)")
ggplot(df, aes(date, Rain)) + geom_line() + labs(x = "", y = "Rain (mm/month)")
ggplot(df1, aes(date, Baseflow)) + geom_line() + labs(x = "", y = "Rain (mm/month)")
plot(df$Baseflow,df$Rain)
df1 <- data_frame(date = seq_date,Totflow=flowR1$OUT$tot, TotET=flowR1$OUT$totaet,Srufflow = flowR1$SURF,Baseflow=flowR1$BASE,Rain=Rain_mean[589:744])

```
